### ISSUE TITLE
License in package.xml

### ISSUE THREAD

**Issue by shr-project** [ros2-gbp/orocos_kinematics_dynamics-release#2]
Can you please include the license version in package.xml?

Currently
https://github.com/ros2-gbp/orocos_kinematics_dynamics-release/blob/release/dashing/orocos_kdl/package.xml#L9
says only LGPL, while:
https://github.com/ros2-gbp/orocos_kinematics_dynamics-release/blob/release/dashing/orocos_kdl/COPYING
says LGPL-2.1

superflore maps this to LGPL-2 in:
https://github.com/ros-infrastructure/superflore/blob/master/superflore/utils.py#L179
and LGPL-2 isn't valid SPDX Identifier in:
https://spdx.org/licenses/
so it would be better to declare the license correctly at the source - in package.xml.

**Comment by nuclearsandwich** [comment]
Thanks for raising the issue @shr-project 

This repository does not contain the versioned source for orocos_kdl for ROS 2, which is itself forked from https://github.com/orocos/orocos_kinematics_dynamics

I would suggest contributing a pull request to https://github.com/orocos/orocos_kinematics_dynamics updating the license identifier there, then letting us know via GitHub issue on https://github.com/ros2/orocos_kdl (you may @-mention me directly) that the license identifier has been updated upstream and we should cherry pick the change.

Once that's done this repository and the released version of orocos_kdl for ROS 2 will be automatically updated to include the updated license identifier.

I would also suggest opening an issue on superflore advising its maintainers that it is generating invalid license identifiers.

I'm going to close the issue here since there is no action required on this repository.
